package effectivejava.chapter2.item5.anonymousclasses;

public class HelloWorldAnonymousClasses {

    interface HelloWorld {
        public void greet();
        public void greetSomeone(String someone);
    }

    //It must  be final (values copied in via the autogenerated constructor)
    public void setValue(final String hello) {
        HelloWorld helloWorld = new HelloWorld() {
            String someOne = "Scott";
            @Override
            public void greet() {
                System.out.println(hello);
                greetSomeone(someOne);
            }

            @Override
            public void greetSomeone(String someone) {
                System.out.println(someone);
            }
        };
        helloWorld.greet();

    };

    public void sayHello() {
        class EnglishGreeting implements HelloWorld {
            String name = "world";
            public void greet() {
                greetSomeone("world");
            }
            public void greetSomeone(String someone) {
                name = someone;
                System.out.println("Hello " + name);
            }
        }

        HelloWorld englishGreeting = new EnglishGreeting();

        HelloWorld frenchGreeting = new HelloWorld() {
            String name = "tout le monde";
            public void greet() {
                greetSomeone("tout le monde");
            }
            public void greetSomeone(String someone) {
                name = someone;
                System.out.println("Salut " + name);
            }
        };

        HelloWorld spanishGreeting = new HelloWorld() {
            String name = "mundo";
            public void greet() {
                greetSomeone("mundo");
            }
            public void greetSomeone(String someone) {
                name = someone;
                System.out.println("Hola, " + name);
            }
        };
        englishGreeting.greet();
        frenchGreeting.greetSomeone("Fred");
        spanishGreeting.greet();


        HelloWorld chineseGreeting = new HelloWorld() {
            public String name = "world";
            public final String accessByChineseGreeting = "world";
            @Override
            public void greet() {
                greetSomeone("world");
            }

            @Override
            public void greetSomeone(String someone) {
                name = someone;
                System.out.println("Hello " + name);
            }
        };



    }

    public static void main(String... args) {
        HelloWorldAnonymousClasses myApp =
                new HelloWorldAnonymousClasses();
        myApp.sayHello();
        myApp.setValue("Final variable");
    }
}
